### ISSUE TITLE
System.ArgumentException: No endpoints specified (Parameter 'configuration')

### ISSUE THREAD

**Issue by elkay235** [PluralKit/PluralKit#556]
I cannot run the most recent commit of PluralKit in my test environment.

When echoing the console, it throws the following:
```[02:19:24.332] FTL Error while running bot
System.ArgumentException: No endpoints specified (Parameter 'configuration')
   at StackExchange.Redis.ConnectionMultiplexer.PrepareConfig(Object configuration, Boolean sentinel) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 939
   at StackExchange.Redis.ConnectionMultiplexer.ConnectAsync(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 875
   at StackExchange.Redis.ConnectionMultiplexer.ConnectAsync(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 852
   at PluralKit.Core.RedisService.InitAsync(CoreConfig config) in C:\Users\Administrator\Desktop\EcoKit ACDS Update\PluralKit.Core\Services\RedisService.cs:line 11
   at PluralKit.Bot.Init.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in C:\Users\Administrator\Desktop\EcoKit ACDS Update\PluralKit.Bot\Init.cs:line 56
--- End of stack trace from previous location ---
   at PluralKit.Bot.Init.RunWrapper(IContainer services, Func`2 taskFunc) in C:\Users\Administrator\Desktop\EcoKit ACDS Update\PluralKit.Bot\Init.cs:line 135
[02:19:24.831] INF Received SIGKILL event, attempting graceful shutdown...
```

I'm not familiar enough to understand what is missing besides a parameter. Either that, or I am misinterpreting. Any pointers would be helpful. Thanks.

**Comment by rladenson** [comment]
Are you maybe missing your pluralkit.conf file?

**Comment by elkay235** [comment]
Doesn't even get a chance to read it before the error is thrown. I deleted the config file outright and threw the exact same error.

**Comment by u1f408** [comment]
Are you sure you've specified the `RedisAddr` in the config?

**Comment by elkay235** [comment]
Thats exactly it. What function does redis serve for PluralKit now? I haven't kept up with the updates.
